# Decodificación de variables categóricas ENIGH

Esta revisión parte de `data/interim/revision_2/`, usa los PDFs oficiales `doc_2018.pdf`, `doc_2020.pdf`, `doc_2022.pdf` y `doc_2024.pdf`, y genera `data/interim/revision_3/` con columnas descriptivas `_desc` únicamente cuando los códigos observados tienen mapping oficial por año.

## Método

- Las fichas de la sección 2.3 se leen con `pdfplumber` y se extraen filas `Valor -> Etiqueta`.
- Las variables que remiten a catálogos de la sección 2.4 se enlazan sólo cuando el catálogo está localizado en el mismo PDF.
- La validación compara códigos observados contra códigos documentados por año, tabla y variable.
- Una variable se decodifica sólo si sus códigos observados quedan cubiertos; la variable original se conserva.

In [1]:
from pathlib import Path
import pandas as pd

ROOT = Path("..").resolve()
REV3 = ROOT / "data" / "interim" / "revision_3"

catalogo = pd.read_csv(REV3 / "catalogo_categoricas_enigh.csv")
estabilidad = pd.read_csv(REV3 / "matriz_estabilidad_categoricas.csv")
validacion = pd.read_csv(REV3 / "validacion_mappings_categoricas.csv")
inventario = pd.read_csv(REV3 / "inventario_variables_revision_3.csv")

print("Catalogo:", catalogo.shape)
print("Estabilidad:", estabilidad.shape)
print("Validacion:", validacion.shape)
print("Inventario:", inventario.shape)

Catalogo: (4406, 12)
Estabilidad: (688, 8)
Validacion: (1296, 11)
Inventario: (558, 6)

In [2]:
catalogo.query("tabla == 'poblacion' and variable in ['sexo','alfabetism','asis_esc','edo_conyug','nivelaprob','parentesco','lenguaind','residencia']").head(80)

,anio,tabla,variable,tipo_documentado,codigo,etiqueta,rango,definicion,catalogo_referencia,orden_categoria,fuente,origen_mapping
281,2018,poblacion,parentesco,C (3),101,Jefe(a),Catálogo de parentesco,"conyugal, por consanguinidad, adopción,",catalogo_parentesco,NaN,doc_2018.pdf p.179,catalogo_externo_pdf
282,2018,poblacion,parentesco,C (3),102,Persona sola,Catálogo de parentesco,"conyugal, por consanguinidad, adopción,",catalogo_parentesco,NaN,doc_2018.pdf p.179,catalogo_externo_pdf
283,2018,poblacion,parentesco,C (3),201,"Esposo(a), compañero(a), cónyuge, pareja, mari...",Catálogo de parentesco,"conyugal, por consanguinidad, adopción,",catalogo_parentesco,NaN,doc_2018.pdf p.179,catalogo_externo_pdf
284,2018,poblacion,parentesco,C (3),202,Concubino(a),Catálogo de parentesco,"conyugal, por consanguinidad, adopción,",catalogo_parentesco,NaN,doc_2018.pdf p.179,catalogo_externo_pdf
285,2018,poblacion,parentesco,C (3),203,Amasio(a),Catálogo de parentesco,"conyugal, por consanguinidad, adopción,",catalogo_parentesco,NaN,doc_2018.pdf p.179,catalogo_externo_pdf
...,...,...,...,...,...,...,...,...,...,...,...,...
480,2018,poblacion,nivelaprob,C (1),6,Carrera técnica o comercial,"{0,...,9}",integrante del hogar de 3 o más años dentro de...,NaN,6,doc_2018.pdf p.74,ficha_variable
481,2018,poblacion,nivelaprob,C (1),7,Profesional,"{0,...,9}",integrante del hogar de 3 o más años dentro de...,NaN,7,doc_2018.pdf p.74,ficha_variable
482,2018,poblacion,nivelaprob,C (1),8,Maestría,"{0,...,9}",integrante del hogar de 3 o más años dentro de...,NaN,8,doc_2018.pdf p.74,ficha_variable
483,2018,poblacion,nivelaprob,C (1),9,Doctorado,"{0,...,9}",integrante del hogar de 3 o más años dentro de...,NaN,9,doc_2018.pdf p.74,ficha_variable
496,2018,poblacion,residencia,C (2),01,Aguascalientes,Catálogo de residencia,"hogar, 5 años antes del momento de la ¿Hace 5 ...",catalogo_residencia,NaN,doc_2018.pdf p.180,catalogo_externo_pdf

In [3]:
pd.read_csv(REV3 / 'muestra_poblacion_prioritaria.csv')

,anio,tabla,variable,observados,documentados,mapeados,sin_mapping,codigos_sin_mapping,documentados_no_observados,normalizaciones_para_mapping,tiene_mapping
0,2018,poblacion,alfabetism,2,2,2,0,NaN,0,NaN,True
1,2018,poblacion,asis_esc,2,2,2,0,NaN,0,NaN,True
2,2018,poblacion,edo_conyug,6,6,6,0,NaN,0,NaN,True
3,2018,poblacion,etnia,2,2,2,0,NaN,0,NaN,True
4,2018,poblacion,hablaind,2,2,2,0,NaN,0,NaN,True
5,2018,poblacion,lenguaind,84,0,0,84,0111; 0113; 0114; 0115; 0121; 0131; 0200; 0211...,0,NaN,False
6,2018,poblacion,nivelaprob,10,10,10,0,NaN,0,NaN,True
7,2018,poblacion,parentesco,34,63,34,0,NaN,29,NaN,True
8,2018,poblacion,residencia,34,34,34,0,NaN,0,NaN,True
9,2018,poblacion,sexo,2,2,2,0,NaN,0,NaN,True
10,2020,poblacion,alfabetism,2,2,2,0,NaN,0,NaN,True
11,2020,poblacion,asis_esc,2,2,2,0,NaN,0,NaN,True
12,2020,poblacion,edo_conyug,6,6,6,0,NaN,0,NaN,True
13,2020,poblacion,etnia,2,2,2,0,NaN,0,NaN,True
14,2020,poblacion,hablaind,2,2,2,0,NaN,0,NaN,True
15,2020,poblacion,lenguaind,89,98,89,0,NaN,9,NaN,True
16,2020,poblacion,nivelaprob,10,10,10,0,NaN,0,NaN,True
17,2020,poblacion,parentesco,33,63,33,0,NaN,30,NaN,True
18,2020,poblacion,residencia,34,34,34,0,NaN,0,NaN,True
19,2020,poblacion,sexo,2,2,2,0,NaN,0,NaN,True
20,2022,poblacion,alfabetism,2,2,2,0,NaN,0,NaN,True
21,2022,poblacion,asis_esc,2,2,2,0,NaN,0,NaN,True
22,2022,poblacion,edo_conyug,6,6,6,0,NaN,0,NaN,True
23,2022,poblacion,etnia,2,2,2,0,NaN,0,NaN,True
24,2022,poblacion,hablaind,2,2,2,0,NaN,0,NaN,True
25,2022,poblacion,lenguaind,90,90,90,0,NaN,0,NaN,True
26,2022,poblacion,nivelaprob,10,10,10,0,NaN,0,NaN,True
27,2022,poblacion,parentesco,40,62,40,0,NaN,22,NaN,True
28,2022,poblacion,residencia,34,34,34,0,NaN,0,NaN,True
29,2022,poblacion,sexo,2,2,2,0,NaN,0,NaN,True
30,2024,poblacion,alfabetism,2,2,2,0,NaN,0,NaN,True
31,2024,poblacion,asis_esc,2,2,2,0,NaN,0,NaN,True
32,2024,poblacion,edo_conyug,8,8,8,0,NaN,0,NaN,True
33,2024,poblacion,etnia,2,2,2,0,NaN,0,NaN,True
34,2024,poblacion,hablaind,2,2,2,0,NaN,0,NaN,True
35,2024,poblacion,lenguaind,85,85,85,0,NaN,0,NaN,True
36,2024,poblacion,nivelaprob,11,11,11,0,NaN,0,0->00; 1->01; 2->02; 3->03; 4->04; 5->05; 6->0...,True
37,2024,poblacion,parentesco,42,62,42,0,NaN,20,NaN,True
38,2024,poblacion,residencia,34,34,34,0,NaN,0,NaN,True
39,2024,poblacion,sexo,2,2,2,0,NaN,0,NaN,True

In [4]:
estabilidad['estado'].value_counts(dropna=False)

estado
no disponible en todos los años    395
estable                            207
categorías diferentes               86
Name: count, dtype: int64

In [5]:
validacion.query('sin_mapping > 0').head(60)

,anio,tabla,variable,observados,documentados,mapeados,sin_mapping,codigos_sin_mapping,documentados_no_observados,normalizaciones_para_mapping,tiene_mapping
22,2018,hogares,anio_aspir,37,1,0,37,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,1,NaN,True
23,2018,hogares,anio_auto,52,1,1,51,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,0,NaN,True
24,2018,hogares,anio_bici,57,1,1,56,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,0,NaN,True
25,2018,hogares,anio_canoa,32,1,0,32,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,1,NaN,True
26,2018,hogares,anio_carret,36,1,1,35,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,0,NaN,True
27,2018,hogares,anio_compu,29,1,1,28,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,0,NaN,True
28,2018,hogares,anio_dvd,32,1,0,32,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,1,NaN,True
29,2018,hogares,anio_ester,49,1,1,48,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,0,NaN,True
30,2018,hogares,anio_estuf,66,1,1,65,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,0,NaN,True
31,2018,hogares,anio_impre,27,1,0,27,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,1,NaN,True
32,2018,hogares,anio_juego,25,1,0,25,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,1,NaN,True
33,2018,hogares,anio_lavad,50,1,1,49,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,0,NaN,True
34,2018,hogares,anio_licua,59,1,1,58,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,0,NaN,True
35,2018,hogares,anio_maqui,69,1,1,68,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,0,NaN,True
36,2018,hogares,anio_micro,39,1,1,38,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,0,NaN,True
37,2018,hogares,anio_moto,38,1,1,37,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,0,NaN,True
38,2018,hogares,anio_otro,25,1,0,25,00; 01; 03; 06; 07; 08; 09; 10; 11; 12; 13; 14...,1,NaN,True
39,2018,hogares,anio_pickup,49,1,1,48,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,0,NaN,True
40,2018,hogares,anio_planc,56,1,1,55,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,0,NaN,True
41,2018,hogares,anio_radio,53,1,1,52,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,0,NaN,True
42,2018,hogares,anio_refri,56,1,1,55,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,0,NaN,True
43,2018,hogares,anio_tosta,44,1,1,43,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,0,NaN,True
44,2018,hogares,anio_trici,32,1,0,32,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,1,NaN,True
45,2018,hogares,anio_tva,52,1,1,51,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,0,NaN,True
46,2018,hogares,anio_tvd,26,1,0,26,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,1,NaN,True
47,2018,hogares,anio_van,47,1,1,46,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,0,NaN,True
48,2018,hogares,anio_venti,51,1,1,50,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,0,NaN,True
56,2018,hogares,diconsa,3,3,2,1,9,1,NaN,True
57,2018,hogares,frec_dicon,3,0,0,3,1; 2; 3,0,NaN,False
66,2018,hogares,num_aspir,6,0,0,6,0; 1; 2; 3; 4; 6,0,NaN,False
67,2018,hogares,num_compu,12,0,0,12,0; 1; 10; 18; 2; 3; 4; 5; 6; 7; 8; 9,0,NaN,False
68,2018,hogares,num_dvd,7,0,0,7,0; 1; 10; 2; 3; 4; 5,0,NaN,False
69,2018,hogares,num_ester,10,0,0,10,0; 1; 10; 15; 2; 3; 4; 5; 7; 8,0,NaN,False
70,2018,hogares,num_estuf,12,0,0,12,0; 1; 10; 15; 2; 3; 35; 4; 5; 6; 7; 9,0,NaN,False
71,2018,hogares,num_impre,8,0,0,8,0; 1; 2; 3; 4; 41; 5; 8,0,NaN,False
72,2018,hogares,num_juego,11,0,0,11,0; 1; 12; 2; 3; 4; 5; 6; 7; 8; 9,0,NaN,False
73,2018,hogares,num_lavad,11,0,0,11,0; 1; 11; 15; 2; 3; 4; 5; 6; 7; 9,0,NaN,False
74,2018,hogares,num_licua,15,0,0,15,0; 1; 10; 11; 14; 18; 2; 20; 3; 4; 5; 6; 7; 8; 9,0,NaN,False
75,2018,hogares,num_maqui,11,0,0,11,0; 1; 10; 11; 2; 3; 4; 42; 5; 6; 7,0,NaN,False
76,2018,hogares,num_micro,8,0,0,8,0; 1; 2; 20; 3; 4; 7; 8,0,NaN,False
77,2018,hogares,num_planc,13,0,0,13,0; 1; 10; 14; 15; 17; 2; 3; 4; 5; 6; 7; 8,0,NaN,False
78,2018,hogares,num_radio,13,0,0,13,0; 1; 15; 16; 2; 25; 3; 32; 4; 5; 6; 8; 9,0,NaN,False
79,2018,hogares,num_refri,13,0,0,13,0; 1; 10; 15; 2; 20; 3; 30; 4; 5; 6; 7; 9,0,NaN,False
80,2018,hogares,num_tosta,5,0,0,5,0; 1; 2; 3; 4,0,NaN,False
81,2018,hogares,num_tva,10,0,0,10,0; 1; 12; 16; 2; 3; 4; 5; 6; 7,0,NaN,False
82,2018,hogares,num_tvd,13,0,0,13,0; 1; 10; 14; 17; 2; 3; 4; 5; 6; 7; 8; 9,0,NaN,False
83,2018,hogares,num_venti,17,0,0,17,0; 1; 10; 11; 12; 13; 14; 15; 17; 2; 3; 4; 5; ...,0,NaN,False
110,2018,poblacion,conyuge_id,18,1,1,17,01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11; 12...,0,NaN,True
120,2018,poblacion,hijos_sob,19,2,2,17,0; 10; 11; 12; 13; 14; 15; 16; 17; 18; 3; 4; 5...,0,NaN,True
135,2018,poblacion,lenguaind,84,0,0,84,0111; 0113; 0114; 0115; 0121; 0131; 0200; 0211...,0,NaN,False
137,2018,poblacion,madre_id,19,1,1,18,01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11; 12...,0,NaN,True
172,2018,poblacion,padre_id,17,1,1,16,01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11; 12...,0,NaN,True
184,2018,poblacion,prob_anio,59,1,0,59,1950; 1952; 1953; 1958; 1960; 1965; 1966; 1967...,1,NaN,True
227,2018,poblacion,trabajo_mp,2,0,0,2,1; 2,0,NaN,False
301,2018,viviendas,hog_dueno1,3,1,0,3,1; 2; 3,1,NaN,True
302,2018,viviendas,hog_dueno2,2,1,0,2,1; 2,1,NaN,True
308,2018,viviendas,num_dueno1,11,1,0,11,01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11,1,NaN,True
309,2018,viviendas,num_dueno2,6,1,0,6,01; 02; 03; 04; 05; 06,1,NaN,True
345,2020,hogares,anio_aspir,41,1,1,40,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,0,NaN,True
346,2020,hogares,anio_auto,53,1,0,53,00; 01; 02; 03; 04; 05; 06; 07; 08; 09; 10; 11...,1,NaN,True

In [6]:
inventario.query("decodificada == 'Sí'").head(80)

,tabla,variable,tipo_conceptual,decodificada,estable_4_anios,observacion
4,concentradohogar,tam_loc,categórica ordinal,Sí,estable,Decodificada con mapping oficial por año.
5,concentradohogar,est_socio,categórica ordinal,Sí,categorías diferentes,Decodificada con mapping oficial por año.
9,concentradohogar,clase_hog,categórica nominal,Sí,categorías diferentes,Decodificada con mapping oficial por año.
10,concentradohogar,sexo_jefe,categórica nominal,Sí,estable,Decodificada con mapping oficial por año.
12,concentradohogar,educa_jefe,categórica nominal,Sí,estable,Decodificada con mapping oficial por año.
...,...,...,...,...,...,...
300,poblacion,gradoaprob,categórica ordinal,Sí,categorías diferentes,Decodificada con mapping oficial por año.
301,poblacion,antec_esc,categórica nominal,Sí,categorías diferentes,Decodificada con mapping oficial por año.
302,poblacion,residencia,código de catálogo,Sí,categorías diferentes,Decodificada con mapping oficial por año.
303,poblacion,edo_conyug,categórica nominal,Sí,categorías diferentes,Decodificada con mapping oficial por año.
304,poblacion,pareja_hog,categórica nominal,Sí,estable,Decodificada con mapping oficial por año.

In [7]:
pob = pd.read_csv(REV3 / 'poblacion_decodificada_2018_2024.csv.gz', nrows=20)
pob[[c for c in ['anio','sexo','sexo_desc','alfabetism','alfabetism_desc','asis_esc','asis_esc_desc','edo_conyug','edo_conyug_desc','nivelaprob','nivelaprob_desc'] if c in pob.columns]].head()

,anio,sexo,sexo_desc,alfabetism,alfabetism_desc,asis_esc,asis_esc_desc,edo_conyug,edo_conyug_desc,nivelaprob,nivelaprob_desc
0,2018,1,Hombre,1,Sí,2,No,2.0,Está casado(a),2,Primaria
1,2018,2,Mujer,1,Sí,2,No,2.0,Está casado(a),2,Primaria
2,2018,1,Hombre,1,Sí,2,No,6.0,Está soltero(a),4,Preparatoria o bachillerato
3,2018,1,Hombre,1,Sí,2,No,2.0,Está casado(a),9,Doctorado
4,2018,2,Mujer,1,Sí,2,No,2.0,Está casado(a),7,Profesional